"""Mathematical utilities for pneumatic and electrical calculations.

All functions use SI units unless documented otherwise.
"""

import math
from typing import List


def orifice_flow(
    pressure_upstream: float,
    pressure_downstream: float,
    diameter: float,
    discharge_coefficient: float = 0.6,
    density: float = 1.2,
) -> float:
    """Volumetric flow rate (m^3/s) through an orifice.

    Uses the incompressible approximation::

        Q = C_d * A * sqrt(2 * delta_p / rho)

    :param pressure_upstream: upstream pressure (Pa, gauge)
    :param pressure_downstream: downstream pressure (Pa, gauge)
    :param diameter: orifice diameter (m)
    :param discharge_coefficient: discharge coefficient C_d
    :param density: fluid density (kg/m^3)
    """
    delta_p = pressure_upstream - pressure_downstream
    if delta_p <= 0.0:
        return 0.0
    area = math.pi * (diameter / 2.0) ** 2
    return discharge_coefficient * area * math.sqrt(2.0 * delta_p / density)


def cylinder_area(bore: float) -> float:
    """Piston area (m^2) of a cylinder with the given bore diameter (m)."""
    return math.pi * (bore / 2.0) ** 2


def cylinder_force(pressure: float, bore: float) -> float:
    """Extension force (N) generated by a pressure (Pa) on a given bore."""
    return pressure * cylinder_area(bore)


def ohms_law(voltage: float, resistance: float) -> float:
    """Current (A) through a resistance (ohms) at a given voltage (V)."""
    if resistance == 0.0:
        return float("inf") if voltage != 0.0 else 0.0
    return voltage / resistance


def series_resistance(resistances: List[float]) -> float:
    """Equivalent resistance (ohms) of resistors in series."""
    return sum(resistances)


def parallel_resistance(resistances: List[float]) -> float:
    """Equivalent resistance (ohms) of resistors in parallel."""
    inverse_sum = sum(1.0 / r for r in resistances if r != 0.0)
    if inverse_sum == 0.0:
        return float("inf")
    return 1.0 / inverse_sum
